# Generated by Django 5.0 on 2024-09-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Podcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("host", models.CharField(max_length=255)),
                ("cover_image", models.URLField(blank=True)),
                ("audio_file", models.URLField(blank=True)),
                ("category", models.CharField(max_length=100)),
                ("language", models.CharField(max_length=50)),
                ("publish_date", models.DateField(auto_now_add=True)),
                ("duration", models.DurationField()),
                ("is_explicit", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="podcasts", to="podcast.tag"
                    ),
                ),
            ],
        ),
    ]
